name: Build SunamoArgs

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoArgs
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoArgs/SunamoArgs.csproj

    - name: Build
      run: dotnet build SunamoArgs/SunamoArgs.csproj --configuration Release --no-restore

  test:
    name: Test SunamoArgs.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoArgs.Tests/SunamoArgs.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoArgs.Tests/SunamoArgs.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoArgs.Tests/SunamoArgs.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
